---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dapla-ssb-no-v1alpha1-commonclientredirecturi
  failurePolicy: Fail
  name: vcommonclientredirecturi.kb.io
  rules:
  - apiGroups:
    - dapla.ssb.no
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - commonclientredirecturis
  sideEffects: None
