# permissions for end users to view commonclientredirecturis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commonclientredirecturi-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dapla-operator
    app.kubernetes.io/part-of: dapla-operator
    app.kubernetes.io/managed-by: kustomize
  name: commonclientredirecturi-viewer-role
rules:
- apiGroups:
  - dapla.ssb.no
  resources:
  - commonclientredirecturis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dapla.ssb.no
  resources:
  - commonclientredirecturis/status
  verbs:
  - get
